### ISSUE TITLE
The docs/ directory should be a vaild Jekyll site for github pages

### ISSUE THREAD

**Issue by alexlovelltroy** [Cray-HPE/cray-site-init#2]
Currently, the `release` target in the Makefile outputs a bunch of markdown files, but doesn't take the logical next step(s) of turning them into a functional Github Pages website.  We should fix this so that users can easily browse the docs.

**Comment by jacobsalmela** [comment]
Fixed in https://github.com/Cray-HPE/cray-site-init/commit/ee0dec84e4af5d4772b1948242b29ee408b42744
