### ISSUE TITLE
Update to GoLang 1.16

### ISSUE THREAD

**Issue by rustydb** [Cray-HPE/cray-site-init#4]
We should probably update from 1.14 to 1.15 or 1.16 before Shasta 1.5 ships. There are numerous improvements, and optimizations in the jump from 1.14 to 1.15 alone.

- [GoLang 1.15 Release Notes](https://golang.org/doc/go1.15)
- [GoLang 1.16 Release Notes](https://golang.org/doc/go1.16)

**Comment by rustydb** [comment]
Blocked on pipeline support of newer-than-1.14. DST-7567 was created.

**Comment by jacobsalmela** [comment]
Fixed in the above ticket.
